baseURL = "https://engelsystem.de/doc/"
theme = "relearn"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "en"
    title = "Engelsystem Documentation"

  [languages.de]
    weight = 2
    languageName = "Deutsch"
    languageCode = "de"
    title = "Engelsystem Dokumentation"

[params]
themeVariant = "blue"
editURL = "https://github.com/engelsystem/engelsystem-doc/tree/main/content/"
custom_css = [ "engelsystem.css" ]
titleSeparator = "-"
disableLandingPageButton = true

[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[markup.goldmark.renderer]
  unsafe = true

[[menu.shortcuts]]
name = "<i class='icon-icon_angel'></i> Website"
url = "https://engelsystem.de"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Engelsystem"
identifier = "ds"
url = "https://github.com/engelsystem/engelsystem"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Documentation"
url = "https://github.com/engelsystem/engelsystem-doc"
weight = 30
